import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const ICONS = [
  { file: 'x-mark', name: 'XMarkIcon' },
  { file: 'plus', name: 'PlusIcon' },
  { file: 'check', name: 'CheckIcon' },
];

const outlineDir = resolve(dirname(require.resolve('heroicons/package.json')), '24', 'outline');
const outDir = resolve(root, 'src', 'icons');

function toCamel(name) {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

mkdirSync(outDir, { recursive: true });

const generated = [];

for (const { file, name } of ICONS) {
  const svg = readFileSync(resolve(outlineDir, `${file}.svg`), 'utf8');
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .trim()
    .replace(/([a-z-]+)="/g, (_, attr) => `${toCamel(attr)}="`);

  const content = `// @generated by scripts/gen-icons.mjs — do not edit
import type { SVGProps } from 'react';

export function ${name}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} {...props}>
      ${inner}
    </svg>
  );
}
`;

  writeFileSync(resolve(outDir, `${name}.tsx`), content);
  generated.push(name);
}

const index = `${generated.map((name) => `export { ${name} } from './${name}';`).join('\n')}\n`;

writeFileSync(resolve(outDir, 'index.ts'), index);
console.log(`Generated icons: ${generated.join(', ')}`);
