ServerName food.dhemeira.hu

Alias /api /srv/backend/api

<Directory /srv/backend/api>
    Require all granted
</Directory>

<Directory /var/www/html>
    AllowOverride None
    Require all granted
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/api/
    RewriteRule ^ /index.html [L]
</Directory>